// Output & sharing (Bible §15, Layer 6): print view, PDF file, de-identifiable share text.

import { FIELDS, SECTIONS, FIELD, NA, isEmpty, withUnit, VERSION } from './schema.js';

const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const fmt = iso => (iso ? new Date(iso).toLocaleString('en-GB', { dateStyle: 'medium', timeStyle: 'short' }) : '-');

export function maskName(n) { return String(n || '').split(/\s+/).filter(Boolean).map(w => w[0].toUpperCase() + '.').join(' '); }
export function maskId(id) { const s = String(id || ''); return s.length > 3 ? '•'.repeat(s.length - 3) + s.slice(-3) : s ? '•••' : ''; }

/** Structured, clinically readable view of a record (shared by print, PDF and share). */
export function recordView(rec, { deidentify = false } = {}) {
  const v = { ...rec.values };
  if (deidentify) { v.patientName = maskName(v.patientName); v.patientId = maskId(v.patientId); v.phone = v.phone ? '(withheld)' : ''; }
  const out = [];
  for (const s of SECTIONS) {
    if (s.id === 'D') continue;
    const rows = [], notAssessed = [];
    for (const f of FIELDS.filter(x => x.sec === s.id && !x.hidden && x.id !== 'sbar')) {
      if (f.type === 'tri') {
        if (v[f.id] === NA) { if (!f.detail || isEmpty(f.detail, v[f.detail])) notAssessed.push(f.label); continue; }
        rows.push([f.label, v[f.id] + (f.detail && v[f.detail] ? ` - ${v[f.detail]}` : '')]);
        continue;
      }
      if (FIELDS.some(t => t.detail === f.id)) continue; // printed with its parent
      if (f.id === 'sugar' && v.sugar) { rows.push([`Blood sugar (${v.sugarType || 'RBS'})`, withUnit('sugar', v)]); continue; }
      const val = withUnit(f.id, v);
      if (val && !isEmpty(f.id, v[f.id])) rows.push([f.label, val]);
      else if (f.req === 'critical') rows.push([f.label, 'NOT RECORDED']);
    }
    out.push({ id: s.id, title: s.title, rows, notAssessed });
  }
  return { v, sections: out };
}

export function printHTML(rec, chk, auditRows = []) {
  const { sections } = recordView(rec);
  const flags = chk?.flags || [];
  const acks = rec.meta.flagAcks || {};
  return `
  <div class="pv-head">
    <div><div class="pv-brand">OphthaCheck</div><div class="pv-sub">Ophthalmic nursing clerking record</div></div>
    <div class="pv-meta"><b>${esc(rec.recordId)}</b> · v${rec.version}<br>Status: <b>${esc(rec.status)}</b><br>${fmt(rec.updatedAt)}</div>
  </div>
  ${flags.length ? `<div class="pv-flags"><b>Red flags</b>${flags.map(f => `<div>${f.level === 'emergency' ? 'EMERGENCY' : 'URGENT'}: ${esc(f.title)} - ${esc(f.evidence)}${acks[f.id] ? ` <i>(acknowledged ${fmt(acks[f.id].at)}${acks[f.id].to ? `, escalated to ${esc(acks[f.id].to)}` : ''})</i>` : ''}</div>`).join('')}</div>` : ''}
  ${sections.map(s => `<section class="pv-sec"><h3>${s.id}. ${esc(s.title)}</h3>
    <table>${s.rows.map(([k, val]) => `<tr><th>${esc(k)}</th><td>${esc(val)}</td></tr>`).join('')}</table>
    ${s.notAssessed.length ? `<p class="pv-na">Not assessed: ${esc(s.notAssessed.join(', '))}</p>` : ''}</section>`).join('')}
  ${rec.values.sbar ? `<section class="pv-sec"><h3>SBAR / handover</h3><pre>${esc(rec.values.sbar)}</pre></section>` : ''}
  <section class="pv-sec pv-sign"><h3>Responsible nurse</h3>
    <table><tr><th>Name</th><td>${esc(rec.nurseName)}</td></tr><tr><th>Rank</th><td>${esc(rec.nurseRank || '-')}</td></tr><tr><th>Staff ID</th><td>${esc(rec.staffId)}</td></tr>
    <tr><th>Created</th><td>${fmt(rec.createdAt)}</td></tr><tr><th>Finalised</th><td>${fmt(rec.finalizedAt)}</td></tr><tr><th>Signature</th><td class="pv-line"></td></tr></table></section>
  ${auditRows.length ? `<section class="pv-sec"><h3>Audit trail</h3><table class="pv-audit">${auditRows.map(a => `<tr><td>${fmt(a.at)}</td><td>${esc(a.action)}</td><td>${esc(a.detail || '')}</td></tr>`).join('')}</table></section>` : ''}
  <p class="pv-foot">Generated by OphthaCheck v${VERSION} prototype. Voice-populated fields were reviewed by the nurse named above. Not validated for unsupervised clinical use.</p>`;
}

let jspdfLoading = null;
function loadJsPDF() {
  if (window.jspdf) return Promise.resolve(window.jspdf);
  jspdfLoading ||= new Promise((res, rej) => { const s = document.createElement('script'); s.src = 'vendor/jspdf.umd.min.js'; s.onload = () => res(window.jspdf); s.onerror = () => rej(new Error('PDF library failed to load')); document.head.appendChild(s); });
  return jspdfLoading;
}

/** Build a PDF file of the record (works offline - library is cached by the service worker). */
export async function makePDF(rec, chk, { deidentify = false } = {}) {
  const { jsPDF } = await loadJsPDF();
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const W = 210, M = 14, CW = W - 2 * M; let y = 16;
  const ensure = h => { if (y + h > 284) { doc.addPage(); y = 16; } };
  const txt = (s, size = 10, style = 'normal', color = [20, 33, 43]) => { doc.setFont('helvetica', style); doc.setFontSize(size); doc.setTextColor(...color); };
  txt('', 16, 'bold', [18, 63, 99]); doc.text('OphthaCheck', M, y);
  txt('', 9, 'normal', [90, 104, 115]); doc.text('Ophthalmic nursing clerking record', M, y + 5);
  doc.text(`${rec.recordId}  ·  v${rec.version}  ·  ${rec.status}`, W - M, y, { align: 'right' });
  doc.text(fmt(rec.updatedAt), W - M, y + 5, { align: 'right' });
  y += 10; doc.setDrawColor(18, 63, 99); doc.setLineWidth(0.6); doc.line(M, y, W - M, y); y += 6;
  const flags = chk?.flags || [];
  if (flags.length) {
    const lines = flags.flatMap(f => doc.splitTextToSize(`${f.level === 'emergency' ? 'EMERGENCY' : 'URGENT'}: ${f.title} - ${f.evidence}`, CW - 6));
    ensure(lines.length * 5 + 8); doc.setFillColor(255, 233, 233); doc.setDrawColor(179, 38, 30); doc.rect(M, y - 4, CW, lines.length * 5 + 6, 'FD');
    txt('', 9.5, 'bold', [150, 20, 20]); lines.forEach((l, i) => doc.text(l, M + 3, y + 1 + i * 5)); y += lines.length * 5 + 6;
  }
  const { sections } = recordView(rec, { deidentify });
  for (const s of sections) {
    ensure(14); txt('', 11.5, 'bold', [18, 63, 99]); doc.text(`${s.id}. ${s.title}`, M, y); y += 2; doc.setDrawColor(207, 217, 224); doc.setLineWidth(0.2); doc.line(M, y, W - M, y); y += 5;
    for (const [k, val] of s.rows) {
      txt('', 9.5); const lines = doc.splitTextToSize(String(val), CW - 62); ensure(lines.length * 4.6 + 1.5);
      txt('', 9, 'normal', [90, 104, 115]); doc.text(k, M, y);
      txt('', 9.5, val === 'NOT RECORDED' ? 'bold' : 'normal', val === 'NOT RECORDED' ? [179, 38, 30] : [20, 33, 43]); doc.text(lines, M + 62, y);
      y += lines.length * 4.6 + 1.5;
    }
    if (s.notAssessed.length) { txt('', 8.5, 'italic', [120, 130, 140]); const l = doc.splitTextToSize(`Not assessed: ${s.notAssessed.join(', ')}`, CW); ensure(l.length * 4 + 2); doc.text(l, M, y); y += l.length * 4 + 2; }
    y += 3;
  }
  if (rec.values.sbar) {
    let sb = rec.values.sbar; if (deidentify) { sb = sb.split(rec.values.patientName || '\u0000').join(maskName(rec.values.patientName)).split(rec.values.patientId || '\u0000').join(maskId(rec.values.patientId)); }
    ensure(14); txt('', 11.5, 'bold', [18, 63, 99]); doc.text('SBAR / handover', M, y); y += 6;
    txt('', 9.5); for (const l of doc.splitTextToSize(sb, CW)) { ensure(5); doc.text(l, M, y); y += 4.6; } y += 3;
  }
  ensure(30); txt('', 11.5, 'bold', [18, 63, 99]); doc.text('Responsible nurse', M, y); y += 6;
  txt('', 9.5); [[`Name`, rec.nurseName], ['Rank', rec.nurseRank || '-'], ['Staff ID', rec.staffId], ['Finalised', fmt(rec.finalizedAt)], ['Signature', '']].forEach(([k, val]) => { txt('', 9, 'normal', [90, 104, 115]); doc.text(k, M, y); txt('', 9.5); doc.text(String(val), M + 62, y); y += 5; });
  doc.line(M + 62, y - 4, M + 130, y - 4);
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) { doc.setPage(i); txt('', 7.5, 'normal', [120, 130, 140]); doc.text(`OphthaCheck v${VERSION} prototype - voice-populated fields reviewed by the nurse named. Not validated for unsupervised clinical use.${deidentify ? ' De-identified copy.' : ''}`, M, 292); doc.text(`${i}/${pages}`, W - M, 292, { align: 'right' }); }
  return doc.output('blob');
}

export function shareText(rec, { deidentify = true, mode = 'sbar' } = {}) {
  const v = rec.values;
  const name = deidentify ? maskName(v.patientName) : v.patientName;
  const id = deidentify ? maskId(v.patientId) : v.patientId;
  let body;
  if (mode === 'sbar' && v.sbar) {
    body = v.sbar;
    if (deidentify) { if (v.patientName) body = body.split(v.patientName).join(name); if (v.patientId) body = body.split(v.patientId).join(id); }
  } else {
    body = recordView(rec, { deidentify }).sections.map(s => [`*${s.id}. ${s.title}*`, ...s.rows.map(([k, val]) => `${k}: ${val}`)].join('\n')).join('\n\n');
  }
  return `OphthaCheck ${rec.recordId} (${rec.status})\nPatient: ${name || '-'} ${id ? `[${id}]` : ''}\n\n${body}\n\n- ${rec.nurseName}${rec.nurseRank ? `, ${rec.nurseRank}` : ''} (${rec.staffId})${deidentify ? '\n(De-identified copy)' : ''}`;
}
